drop table BATF_COLL_MASTER;
create table BATF_COLL_MASTER
(
  BRANCH_ID        VARCHAR2(20 CHAR),
  PLAT_DATE        NUMBER(11) not null,
  PLAT_TIME        NUMBER(11),
  PLAT_TRACE       NUMBER(11) not null,
  LOG_ID           VARCHAR2(60 CHAR),
  LOG_DEV          VARCHAR2(20 CHAR),
  SND_DATE         VARCHAR2(8 CHAR),
  SND_TIME         VARCHAR2(9 CHAR),
  SND_SEQNO        VARCHAR2(32 CHAR),
  TX_STATUS        VARCHAR2(1 CHAR),
  TX_MSG           VARCHAR2(120 CHAR),
  BATCH_ID         VARCHAR2(60 CHAR),
  TOTAL_NUM        NUMBER(11),
  TOTAL_AMT        NUMBER,
  SUCC_NUM         NUMBER(11),
  SUCC_AMT         NUMBER,
  FAIL_NUM         NUMBER(11),
  FAIL_AMT         NUMBER,
  RESERVED         VARCHAR2(255 CHAR)
);

-- Add comments to the table 
COMMENT ON TABLE BATF_COLL_MASTER IS '批量代扣主表';

-- Add comments to the columns 
COMMENT ON COLUMN BATF_COLL_MASTER.BRANCH_ID IS '机构号';
COMMENT ON COLUMN BATF_COLL_MASTER.PLAT_DATE IS '平台日期';
COMMENT ON COLUMN BATF_COLL_MASTER.PLAT_TIME IS '平台时间';
COMMENT ON COLUMN BATF_COLL_MASTER.PLAT_TRACE IS '平台流水';
COMMENT ON COLUMN BATF_COLL_MASTER.LOG_ID IS '日志ID';
COMMENT ON COLUMN BATF_COLL_MASTER.LOG_DEV IS '日志设备';
COMMENT ON COLUMN BATF_COLL_MASTER.SND_DATE IS '发送方日期';
COMMENT ON COLUMN BATF_COLL_MASTER.SND_TIME IS '发送方时间';
COMMENT ON COLUMN BATF_COLL_MASTER.SND_SEQNO IS '发送方流水';
COMMENT ON COLUMN BATF_COLL_MASTER.TX_STATUS 
IS '交易状态：0、登记；1、代扣处理中；2、处理完成；3、结果通知发送完成';
COMMENT ON COLUMN BATF_COLL_MASTER.TX_MSG IS '交易处理信息';
COMMENT ON COLUMN BATF_COLL_MASTER.BATCH_ID IS '批次编号';
COMMENT ON COLUMN BATF_COLL_MASTER.TOTAL_NUM IS '总笔数';
COMMENT ON COLUMN BATF_COLL_MASTER.TOTAL_AMT IS '总金额';
COMMENT ON COLUMN BATF_COLL_MASTER.SUCC_NUM IS '成功总笔数';
COMMENT ON COLUMN BATF_COLL_MASTER.SUCC_AMT IS '成功总金额';
COMMENT ON COLUMN BATF_COLL_MASTER.FAIL_NUM IS '失败总笔数';
COMMENT ON COLUMN BATF_COLL_MASTER.FAIL_AMT IS '失败总金额';
COMMENT ON COLUMN BATF_COLL_MASTER.RESERVED IS '预留';

-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE BATF_COLL_MASTER add PRIMARY KEY (PLAT_DATE, PLAT_TRACE);
CREATE UNIQUE INDEX BATF_COLL_MASTER_INDEX_1 ON BATF_COLL_MASTER (BATCH_ID);